[[runners]]
    name = "docker0"
    url = "https://gitlab.com/"
    token = "GR1348941yhuMYi-ohoxYwCYiisZS"
    executor = "docker"
    [runners.custom_build_dir]
    [runners.cache]
        [runners.cache.s3]
        [runners.cache.gcs]
        [runners.cache.azure]
    [runners.docker]
        tls_verify = false
        image = "docker:stable"
        privileged = true
        disable_entrypoint_overwrite = false
        oom_kill_disable = false
        disable_cache = false
        volumes = ["/cache"]
        shm_size = 0
        network_mode = "host"
        pull_policy = "if-not-present"